### ISSUE TITLE
If you get an SSL error on data download, here's a fixed command

### ISSUE THREAD

**Issue by syllog1sm** [jgontrum/spacy-api-docker#1]
I've had to set up the model hosting stuff afresh, and there are a couple of teething problems, seemingly around SSL. If you have issues with the `python -m spacy.en.download` command, this should work:

`sputnik --name spacy --repository-url http://index.spacy.io install en==1.1.0`

Thanks for publishing this! I've wanted a Docker container for a while, but haven't used Docker, so I never got around to setting it up.

**Comment by jgontrum** [comment]
Thanks for the note! I'm currently working on a new API that's a bit more sophisticated and will include the new command in the next version!
