### ISSUE TITLE
French model not working

### ISSUE THREAD

**Issue by DEVKWS** [jgontrum/spacy-api-docker#13]
docker run -p "127.0.0.1:8080:80" jgontrum/spacyapi:fr

http://localhost:8080/ui

UI loads correctly, however any requests from the sentence entry simply do not return. The loading icon spins and nothing else happens.

I have tried en and en_v2. Both work as they should.

When testing this no other containers were running.

edit: curl commands fail as well.

 curl -s localhost:80/dep -d '{"text":"Bonjour Justin Trudeau.", "model":"fr"}'

{"title":"Dependency parsing failed","description":"'NoneType' object is not callable"}

**Comment by jgontrum** [comment]
I just upgraded the API to use the current stable version of spaCy and the French model works now. Can you please try starting spacyapi:fr_v2 ?

**Comment by DEVKWS** [comment]
It works now :)

thank you for the quick turn around!
