### ISSUE TITLE
DEFECT: Latest docker container is broken - Displacy UI doesn't work

### ISSUE THREAD

**Issue by bigman73** [jgontrum/spacy-api-docker#29]
I had a fully functional spacy docker running from 6 months ago. After downloading the new image today the displacy UI shows up but when entering a sentence it spins forever and doesn't return results.

**Comment by bigman73** [comment]
Related to: https://github.com/jgontrum/spacy-api-docker/issues/27

The error message in Chrome is:
`displacy.js:55 POST http://<IPADDR>:8080/dep/ 404 (Not Found)`

**Comment by peter-hartmann-emrsn** [comment]
The UI seems broken for jgontrum/spacyapi:en_v2 Pulling latest works for me.

The seems ok for jgontrum/spacyapi:latest.

**Comment by FabianL1** [comment]
Broken for me too. Will this be fixed?

**Comment by jgontrum** [comment]
Thanks for the reminder! I just pushed a fix, the UI should be working again.
