### ISSUE TITLE
ISSUE: Docker image starts and then stops after a few seconds

### ISSUE THREAD

**Issue by bigman73** [jgontrum/spacy-api-docker#7]
I followed the instructions and pulled the docker image then ran the container

The container starts to run then stops after a few seconds
The only message visible on the container logs is: "Killed"

Other containers are working just fine.

Running on Windows 7 pro, 64 bit, Oracle VM Virtual Box 5.1.22

Docker version:
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Fri May  5 15:36:11 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 21:43:09 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Comment by w0dm4n** [comment]
I have the same fucking issue DOCKER DEVELOPPER YOU NEED TO GET CANCER AND SUFFER IN HELL

**Comment by jgontrum** [comment]
Go and fix it yourself, then make a pull request. That's how open source works.

And feel yourself reported, your behaviour is a clear violation of GitHubs community guidelines and any human decency.

**Comment by bigman73** [comment]
@jgontrum  I fully agree with your comment to the troll. Such responses have no place in github or anywhere else.

Regardless, can you kindly address the issue that I have raised?
I'd like to use the spacy.io docker image that you have created but running into the issues mentioned in my ticket. Since then I decided to use another parts of speech engine, but I still want to be able to use spacy.
Thanks.

**Comment by teebu** [comment]
I had a similar issue on AWS, i was noticing memory error. My solution was to use a bigger instance, with 2 gigs of ram.

**Comment by jgontrum** [comment]
Yes, these models take up a lot of memory. In the new version of this API I use the smaller english model (~50mb). I think that should prevent this issue to come up too often at least for english.
